#!/usr/bin/env bash
# a script that transfer a file to a server

count=0

#loop through command line arguments
for _ in "$@";
do
	count=$((count + 1))
done

# conditional check for argument count
if [[ $count -lt 3 ]];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 0
fi

file_path=$1
server_ip=$2
username=$3
identity=$4

scp -o StrictHostKeyChecking=no -i "$identity" "$file_path" "$username@$server_ip:~/"
