#!/usr/bin/env bash
# Redirection

sudo apt update
sudo apt install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Redirection
cat << EOF | sed -i '/server_name .*/r /dev/stdin' /etc/nginx/sites-available/default

	location /redirect_me {
		rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
EOF

sudo service nginx restart
