#!/usr/bin/env bash
# Redirection

sudo apt update
sudo apt install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

string='\n\tlocation /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}'

echo -e "$string" > temp_file
sudo sed -i '/server_name .*/ r temp_file' /etc/nginx/sites-enabled/default
sudo rm temp_file

sudo service nginx restart
