#!/usr/bin/env bash
# Redirection

sudo apt update
sudo apt install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo service nginx start

phrase="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $phrase" /etc/nginx/sites-available/default

sudo service nginx restart
