#!/usr/bin/env bash
# Redirection

sudo apt update
sudo apt install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Redirection
sudo sh -c 'cat << EOF | sed -i "/server_name .*/r /dev/stdin" /etc/nginx/sites-available/default

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
EOF'


# error page
sudo sh -c "cat << EOF > /var/www/html/404-page.html
Ceci n'est pas une page
EOF"

sudo sh -c 'cat << EOF | sed -i "/server_name .*/r /dev/stdin" /etc/nginx/sites-available/default

        error_page 404 /404-page.html;

	location = /404-page.html {
                root 404 /var/www/html;
		internal;
        }
EOF'

sudo service nginx restart
