#!/usr/bin/env bash
# Bash script that creates a MySQL backup.
sudo sh -c "mysqldump -uroot -p\"$1\" --all-databases > backup.sql"
current_date=$(date "+%d-%m-%Y")
tar -cvzf "$current_date.tar.gz" backup.sql
