#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

sed -i 's/8080 default/80 default/' /etc/nginx/sites-enabled/default
sudo service nginx restart
